= J-Confs
[![Build Status](https://travis-ci.org/J-Conf-Team/J-Confs.svg?branch=master)](https://travis-ci.org/J-Conf-Team/J-Confs)

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the MIT License, with their permission.

Delivery schedule for 2019 :

Delivery 1 :
	Tasks :
		Update dependencies if possible (Junit, Guava, as well as dependencies of different environments)
		Update package "y2018 "to "y2019"
		Deleting documents in resources that are not used
		Apply best practices with Guava to the existing system :
			Preconditions
			StringBuilder (for toString)
			getResources
		Perform tests using JUnit for the following classes:
			ConferenceWriter
			Conferencereader or Readfileconference
			Shower Conferences
			ReverseGeoCode
		Delete unused classes
		Create packages to better divide the code according to dependencies between classes:
			Mistletoe
			Conference
			Geo
		Apply a Javadoc with defensive programming
		Redefine some exception lifts that are too generic
		Match an Icalendar file to a researcher

Delivery 2 :
	Tasks :
		Modify ConferenceGui with possibility:
			The user selects his iCalendar
			All the conferences of this iCalendar are displayed on the screen
			Possibility to edit an Icalendar conference
			Ability to display a map with the location of a selected conference
			
Delivery 3 :
	Tasks :
		Do the JC functionality :
			Method for filling the fields of the canvas with use of the POI library
			Saving the file
		In the continuity of delivery 2 we can also make the History feature:
			When editing a conference from the GUI, the icalendar file is sent to a remote github repository
			
Delivery 4 :
	Tasks :	
		Continue the History feature
		Do the Peterhead feature
		